
package ui.AdoptionManager;


import model.EcoSystem.CommonMail;
import model.EcoSystem.EcoSystem;
import model.Enterprise.AdoptionEnterprise;
import model.Network.Network;
import model.Organization.AdoptionOperationOrganization;
import model.UserAccount.UserAccount;
import model.WorkQueue.AdopterAuthorizationRequest;
import model.WorkQueue.WorkRequest;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author fanyesun
 */
public class AdoptionManagerWorkArea extends javax.swing.JPanel {

    private JPanel workArea;
    private Network network;
    private EcoSystem ecosystem;
    private AdoptionOperationOrganization organization;
    private AdoptionEnterprise enterprise;

    private UserAccount userAccount;

    /**
     * Creates new form AdoptionManagerWorkArea
     */
    public AdoptionManagerWorkArea(JPanel userProcessContainer, UserAccount account, AdoptionOperationOrganization organization, AdoptionEnterprise enterprise, Network network, EcoSystem ecosystem) {

        initComponents();
        this.ecosystem = ecosystem;
        this.network = network;
        this.enterprise = enterprise;
        this.workArea = userProcessContainer;
        this.userAccount = account;
        this.organization = organization;




        populateTable();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblWorkRequests = new javax.swing.JTable();
        btnApprove = new javax.swing.JButton();
        btnAssign = new javax.swing.JButton();

        setBackground(new java.awt.Color(155, 209, 249));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
       //Adopter Authorization
        lblTitle.setText("Adopter Approval");
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, -1, -1));

        jScrollPane1.setForeground(new java.awt.Color(255, 255, 255));

        tblWorkRequests.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Message", "Sender", "Email", "Organization", "Receiver", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblWorkRequests);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 890, 350));

        btnApprove.setBackground(new java.awt.Color(204, 255, 204));
        btnApprove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icon_approved.png"))); // NOI18N
        btnApprove.setText("Approve");
        btnApprove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApproveActionPerformed(evt);
            }
        });
        add(btnApprove, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 500, -1, -1));

        btnAssign.setBackground(new java.awt.Color(204, 255, 204));
        btnAssign.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icon_assign.png"))); // NOI18N
        btnAssign.setText("Delegate to Me");
        btnAssign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignActionPerformed(evt);
            }
        });
        add(btnAssign, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 500, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnApproveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApproveActionPerformed

        int optionChosen = tblWorkRequests.getSelectedRow();
        //the row which has been selected
        if (optionChosen >= 0) {
            WorkRequest beg = (WorkRequest) tblWorkRequests.getValueAt(optionChosen, 0);
            if (beg.getReceiver() == userAccount) {

                if (beg.getStatus().equalsIgnoreCase("Approved")) {
                    JOptionPane.showMessageDialog(this, "Already approved. Please choose another one.", "Warning", JOptionPane.WARNING_MESSAGE);

                    return;
                } else {
                    beg.setStatus("Approved");
                    populateTable();

                    JOptionPane.showMessageDialog(this, "Account approved", "Information", JOptionPane.INFORMATION_MESSAGE);
                    String title = "Account activation";
                    String message = "Dear Adopter, \nyour account: [" + beg.getSender() + "] has been activated.  \nThank you!";
                    CommonMail.sendEmailMessage(beg.getSender().getEmailId(), title, message);
                }
            } else {
                //show warning
                JOptionPane.showMessageDialog(this, "This request is not delegated to you.", "Warning", JOptionPane.WARNING_MESSAGE);
                return;
            }

        } else {
            //show warning
            JOptionPane.showMessageDialog(this, "You haven't chosen a request yet", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

    }//GEN-LAST:event_btnApproveActionPerformed

    private void btnAssignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignActionPerformed
        // TODO add your handling code here:

        int optionChosen = tblWorkRequests.getSelectedRow();
        //request row which has been selected
        if (optionChosen >= 0) {
            WorkRequest beg = (WorkRequest) tblWorkRequests.getValueAt(optionChosen, 0);
            if (beg.getStatus().equalsIgnoreCase("Approved")) {
                JOptionPane.showMessageDialog(this, "Already completed. Please choose another one.", "Warning", JOptionPane.INFORMATION_MESSAGE);
                return;
            } else {//show warning
                beg.setReceiver(userAccount);
                beg.setStatus("Reviewing");
                populateTable();
            }

        } else {//show warning
            JOptionPane.showMessageDialog(this, "Please choose a request first!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

    }//GEN-LAST:event_btnAssignActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApprove;
    private javax.swing.JButton btnAssign;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblWorkRequests;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {

        DefaultTableModel model = (DefaultTableModel) tblWorkRequests.getModel();
        model.setRowCount(0);

        for (WorkRequest beg : enterprise.getWorkQueue().getWorkRequestList()) {
            if (beg instanceof AdopterAuthorizationRequest) {
                //create new request
                Object[] table = new Object[6];
                table[5] = beg.getStatus();
                table[4] = beg.getReceiver() == null ? null : beg.getReceiver();
                table[3] = beg.getSender().getOrgainization();
                table[2] = beg.getSender().getEmailId();
                table[1] = beg.getSender();
                table[0] = beg;






                model.addRow(table);
            }
        }
    }
}
